steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'australia-southeast1-docker.pkg.dev/instant-medium-424313-b9/testing-docker-repo/my-image:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'australia-southeast1-docker.pkg.dev/instant-medium-424313-b9/testing-docker-repo/my-image:latest']

images:
  - 'australia-southeast1-docker.pkg.dev/instant-medium-424313-b9/testing-docker-repo/my-image:latest'

options:
  logging: 'CLOUD_LOGGING_ONLY'

