name: Deploy Docker Image to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # Replace with the label of your self-hosted runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t my-app:latest .
        docker tag my-app:latest ${{ secrets.DOCKER_USERNAME }}/my-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

  update-deployment:
    runs-on: self-hosted  # Replace with the label of your self-hosted runner
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update Kubernetes deployment
      run: |
        sed -i 's|image: .*|image: '"${{ secrets.DOCKER_USERNAME }}/my-app::${{ github.run_number }}"'|' /home/ubuntu/actions-runner/_work/hello-react-app/hello-react-app/deployment.yaml

    - name: Commit changes
      run: |
        git config --global --add safe.directory /home/ubuntu/actions-runner/_work/hello-react-app/hello-react-app
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add /home/ubuntu/actions-runner/_work/hello-react-app/hello-react-app/deployment.yaml
        git commit -m 'Update Docker image to ${{ secrets.DOCKER_USERNAME }}/my-app:latest'
        git push
