deploy:
  needs: build
  runs-on: ubuntu-latest

  steps:
    - name: Deploy to EC2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
        EC2_INSTANCE_IP: ${{ secrets.EC2_INSTANCE_IP }}
        DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/my-image:latest

      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

        # Connect to EC2 and deploy Docker image
        aws ec2-instance-connect send-ssh-public-key \
          --instance-id $EC2_INSTANCE_ID \
          --availability-zone $AWS_REGION \
          --instance-os-user ec2-user \
          --ssh-public-key file://~/.ssh/id_rsa.pub

        ssh -o StrictHostKeyChecking=no ec2-user@${EC2_INSTANCE_IP} << 'EOF'
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull $DOCKER_IMAGE
          docker stop test || true
          docker rm test || true
          docker run -d --name test -p 80:3000 $DOCKER_IMAGE
        EOF
